#!/bin/bash

# https://stackoverflow.com/a/3063887/9983389
if [ ! -z "$1" ]; then
        pkg=$1
else
        echo "usage: `basename $0` <pkg>"
        exit 1
fi

# https://phoenixnap.com/kb/bash-case-statement
case "$PWD" in
  *x86_64*)
	arch=x86_64;;
  *bcm2836*)
	arch=bcm2836;;
  *)
	arch=x86_64 #default
	echo "defaulting to $arch"
	;;
esac

if [ -d /build ]; then
        # inside Docker shell
	make pkg-$pkg |& tee /build/doc/$pkg.log
else
	if [ ! -d ./buildroot ]; then
		echo "this doesn't seem to be the root"
		exit 1
	fi

	mkdir -p doc
        make ${arch}-build CMD=$pkg |& tee doc/$pkg.log
fi
